### ISSUE TITLE
need urgent help for trac server / gitolite permission

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage_trac_plugin#26] opened 2022-08-31 09:52 UTC
Could please somebody help with the current problem on the trac server ?

**Comment by fchapoton** [comment] 2022-08-31 09:55
This may be related to the paragraph

Important: Finally, the user under which the Trac server runs (e.g. www-data when Trac is run in Apache in the typical configuration) must have an SSH key with R/W access on the gitolite-admin repository hosted on the server given by gitolite_host.

in our README

**Comment by vbraun** [comment] 2022-08-31 14:14
Whats actually failing? The host key of the trac server changed, so that needs to be updated on each account where gitolite is directly accessed

**Comment by fchapoton** [comment] 2022-08-31 14:24
I had to disable the sshkeys plugins in trac.ini, because of this kind of messages
```
2022-08-31 06:25:05,445 Trac[env] ERROR: Exception caught while checking for upgrade: 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/trac/env.py", line 842, in open_environment
    needs_upgrade = env.needs_upgrade()
  File "/usr/local/lib/python2.7/dist-packages/trac/env.py", line 696, in needs_upgrade
    for participant in self.setup_participants:
  File "/usr/local/lib/python2.7/dist-packages/trac/core.py", line 82, in extensions
    components = [component.compmgr[cls] for cls in classes]
  File "/usr/local/lib/python2.7/dist-packages/trac/core.py", line 208, in __getitem__
    component = cls(self)
  File "/usr/local/lib/python2.7/dist-packages/trac/core.py", line 144, in __call__
    self.__init__()
  File "/usr/local/lib/python2.7/dist-packages/sage_trac/sshkeys.py", line 195, in __init__
    self._init_gitolite_admin()
  File "/usr/local/lib/python2.7/dist-packages/sage_trac/sshkeys.py", line 66, in wrapper
    ret = inner_wrapper(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/fasteners/lock.py", line 302, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sage_trac/sshkeys.py", line 52, in inner_method
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sage_trac/sshkeys.py", line 226, in _init_gitolite_admin
    self._update_gitolite_admin()
  File "/usr/local/lib/python2.7/dist-packages/sage_trac/sshkeys.py", line 287, in _update_gitolite_admin
    'repository'.format(out))
TracError: Error updating the gitolite-admin repository: Host key verification failed.
fatal: Could not read from remote repository.
```

Then this provokes other failures. For example, looking for the name of the git repository in the [trac] section of trac.ini, instead of [sage_trac] section.

and then an issue with pygit2 merge command..

**Comment by fchapoton** [comment] 2022-08-31 14:28
Quite a nightmare..
Sorry, but it's hard for me to understand your suggestion. I had checked that www-data (apache account) has the correct rights to access gitolite.

**Comment by vbraun** [comment] 2022-08-31 17:27
It seems like the sshkeys plugin needs fixing, either its not actually running under the www-data account, or there is confusion with the hostkey (there may be multiple keys in .ssh/known_hosts and different implementations use different key versions to check, clear out all trac entries and try again). Probably easiest would be to preserve the host key tho (i.e. copy over the old host keys)

**Comment by embray** [comment] 2022-09-17 17:04
Was this ever resolved? 

When the trac server starts up it tries (if it doesn't already have one) to make a clone of the gitolite-admin repository over SSH: https://github.com/sagemath/sage_trac_plugin/blob/7639efe376bba4da4cabb95a8e7c61708b7479e1/sage_trac/sshkeys.py#L227

If it already has one it won't re-clone it.

It clones the gitolite-admin repository from the host configured in the sage_trace/gitolite_host setting in the configuration, which is probably just `localhost`.  Nevertheless, even for `localhost`, if it's going through SSH the user trying to access that server will have to have valid public key for the host in its `.ssh/known_hosts` as @vbraun wrote.  The user in this case is Apache (www-data).  So you have to make sure that the www-data user has a home directory of some sort and that the server's public key is properly in its known_hosts file.

This is a standard security measure in SSH to mitigate MitM attacks.

Unfortunately, as much good documentation as the gitolite docs have about SSH, it doesn't seem to make any mention of this...

**Comment by fchapoton** [comment] 2022-09-17 18:22
oh, well, this has now been sorted out, somehow. Apparently, despite my best efforts to keep trac working, some people want to switch immediatly to github.

**Comment by dimpase** [comment] 2023-01-27 22:56
For what's worth, `trac-admin` is broken on the server, as it tries to clone `gitolite-admin` repo any time it is asked to do anything. 
```
$ sudo trac-admin /srv/trac/sage_trac permission list
Error: Failed to clone gitolite-admin repository: Cloning into
'/srv/trac/sage_trac/gitolite-admin'...
fatal: 'gitolite-admin' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

as a result, I'm having trouble moving trac to a read-only state in preparation to moving to github.
my current plan is to

1) disable tracext.github.githubloginmodule in trac.ini (we allow
GitHub-authenticated users access to tickets and git tree)
2) point htdigest_file in trac.ini to a file without any actual passwords

I suppose 1)+2)  should make tickets effectively read-only.
To make git tree read-only, one apparently still needs to disable ssh
authentication,
and I can't think of anything less intrusive than

3) removing all the ssh keys uploaded and stored
in the said gitolite-admin git repo (I can push there, and it appears
to effect changes)

--------------------------

I've spent a good part of the day actually understanding what's going on, even [asking Trac devs for help](https://groups.google.com/g/trac-users/c/C_ZFXu39jN4/m/vcyGFFRYAAAJ)

I haven't  realised that it's this homemade stuff that does all this to `trac-admin` - it was certainly left in sorry state after the update to 1.2.  Did `trac-admin` worked before the update?

**Comment by dimpase** [comment] 2023-01-27 22:58
> people want to switch immediatly to github.

people have to clean after some other people, as we see... :-(

**Comment by dimpase** [comment] 2023-01-27 23:13
> When the trac server starts up it tries (if it doesn't already have one) to make a clone of the gitolite-admin repo

@embray - why does it get called every time by `trac-admin` on the server running trac at full speed? Is it due to update to Trac 1.2, which perhaps broke it? Or it never functioned with `trac-admin` ?

**Comment by dimpase** [comment] 2023-01-28 00:03
OK, I gather it's cause I tried running `trac-admin` as root. As myself, after adding myself to the correct group`www-data`, and after changing few permissions in /src/trac/ to group-writeable, I was able to run `trac-admin` meaningfully.

Sorry for noise.

**Closed as completed by dimpase** 2023-01-28 00:03 UTC

**Comment by mkoeppe** [comment] 2023-01-28 08:27
Trac is currently broken, a permissions problem caused by these experiments?

**Comment by dimpase** [comment] 2023-01-28 09:12
I haven't noticed anything - I was not doing "experiments", I was making myself a TRAC_ADMIN using `trac_admin` tool, which was supposed to be working all along. :-)
And I didn't notice anything broken - probably because I was logged on trac in a browser, and it kept showing me tickets just fine...

**Comment by dimpase** [comment] 2023-01-28 09:42
it's back on. I had to manually remove cloned with an incorrect username /srv/trac/sage_trac/gitolite-admin/, and reboot.

Needless to say, it knocked trac-admin tool out again, but, ok...

**Comment by embray** [comment] 2023-02-05 16:36
The Trac/gitolite integration is complicated and requires good understanding of both. Can't promise there are no bugs either as it's all custom code. But yes as @dimpase discovered the gitolite repo has to be owned by the www-data user under which Apache runs, and thus Trac, in order for the git repo to be readable and writeable.
